version: "3.9"

services:
  fastapi_service:
    build:
      context: ./app
      dockerfile: Dockerfile
    hostname: fastapi_service
    container_name: fastapi_service
    depends_on:
      - db_postgres
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    volumes:
      - ./app:/home/app

  cache-redis:
    image: redis:alpine
    hostname: cache-redis
    container_name: cache-redis
    restart: on-failure
    ports:
      - '6379:6379'
    expose:
      - '6379'
    command: redis-server
    volumes:
      - cache:/data

  db_postgres:
    image: postgres:14.3-alpine
    hostname: db_postgres
    container_name: db_postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db_postgres

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:cache-redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - cache-redis

volumes:
  db-postgres:
    driver: local

  cache:
    driver: local
